<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        /*
         * If you are running a version of MySQL older than the 5.7.7 release or MariaDB older than the 10.2.2 release,
         * you may need to manually configure the default string length generated by migrations
         * in order for MySQL to create indexes for them.
         */
        // \Schema::defaultStringLength(191);
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        $this->registerIdeHelperServiceProvider();
    }

    protected function registerIdeHelperServiceProvider()
    {
        if ($this->app->environment() !== 'production') {
            $provider = \Barryvdh\LaravelIdeHelper\IdeHelperServiceProvider::class;

            if (class_exists($provider)) {
                $this->app->register($provider);
            }
        }
    }
}
